-- SOS Game Oracle Database Schema
-- Run via Spring Boot JPA auto-ddl or manually

CREATE SEQUENCE SOS_MATCH_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SOS_MATCH_PLAYER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SOS_MATCH_MOVE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SOS_MATCH (
    MATCH_ID        NUMBER PRIMARY KEY,
    ROOM_CODE       VARCHAR2(10),
    WINNER_TELEGRAM_ID NUMBER,
    GRID_SIZE       NUMBER DEFAULT 6,
    PLAYER_COUNT    NUMBER DEFAULT 2,
    START_TIME      TIMESTAMP,
    END_TIME        TIMESTAMP,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SOS_MATCH_PLAYER (
    MATCH_PLAYER_ID NUMBER PRIMARY KEY,
    MATCH_ID        NUMBER REFERENCES SOS_MATCH(MATCH_ID),
    TELEGRAM_ID     NUMBER NOT NULL,
    PLAYER_NAME     VARCHAR2(100),
    SCORE           NUMBER DEFAULT 0
);

CREATE TABLE SOS_MATCH_MOVE (
    MOVE_ID         NUMBER PRIMARY KEY,
    MATCH_ID        NUMBER REFERENCES SOS_MATCH(MATCH_ID),
    TELEGRAM_ID     NUMBER,
    ROW_INDEX       NUMBER,
    COLUMN_INDEX    NUMBER,
    LETTER          VARCHAR2(1),
    MOVE_TIME       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_SOS_MATCH_ROOM ON SOS_MATCH(ROOM_CODE);
CREATE INDEX IDX_SOS_MATCH_PLAYER_TG ON SOS_MATCH_PLAYER(TELEGRAM_ID);
CREATE INDEX IDX_SOS_MATCH_MOVE_MATCH ON SOS_MATCH_MOVE(MATCH_ID);
